name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose build

      - name: Start DB
        run: docker compose up -d db

      - name: Wait for database
        run: |
          docker compose exec -T db sh -c '
            until pg_isready -U blog_user -d blog_db; do
              sleep 2
            done
          '

      - name: Migrate
        run: docker compose run --rm backend python manage.py migrate

      - name: Test
        run: docker compose run --rm backend pytest -v

      - name: Cleanup
        if: always()
        run: docker compose down -v
